SELECT 
    UDATE,
    SUBSTR(ALVARADATASIVISA, 0 , 4)||'-'||SUBSTR(ALVARADATASIVISA, 5 , 2)||'-'||SUBSTR(ALVARADATASIVISA, 7 , 2) AS ALVARADATASIVISA,
    SUBSTR(ALVARADATA, 0 , 4)||'-'||SUBSTR(ALVARADATA, 5 , 2)||'-'||SUBSTR(ALVARADATA, 7 , 2) AS ALVARADATA,    
    SUBSTR(ALVARADATASANIT, 0 , 4)||'-'||SUBSTR(ALVARADATASANIT, 5 , 2)||'-'||SUBSTR(ALVARADATASANIT, 7 , 2) AS ALVARADATASANIT,        
    SUBSTR(DATACRF, 0 , 4)||'-'||SUBSTR(DATACRF, 5 , 2)||'-'||SUBSTR(DATACRF, 7 , 2) AS DATACRF,            
    ALVARANUMERO, ALVARANUMEROSANIT, ALVARANUMEROSIVISA, ASSOCIATIVISMO1, ASSOCIATIVISMO2, BLOQUEIO, BU, CAIXA_FECHADA, CLI_BAI, CLI_CEP, CLI_CGC, CLI_CID, CLI_COMPL,CLI_EMAIL,CLI_END,CLI_EST,CLI_INE,CLI_LIMITE,CLI_NUM,CLI_RZS,CLI_TEL,CLI_TEL2,COD_REDE,CODIGO,CONDICAOPG,CONTROLADO,CROSSDOCKING,FLAGDISTRIBUIDOR,FLAGFARMACIA,FLAGOUTRATIV,FLAGZONAFRANCA,GRUPO_CONTAS,NOME_FANTASIA,RESPTECNICOCRF,RESPTECNICONOME,TIPOCOBRANCA 
FROM dados-dev.raw_cimed_tech.CADASTRO_CLIENTE_T where udate >= timestamp_add(current_timestamp , INTERVAL -100 DAY)